create table CRM
(
Invoice_id int8, 
Invoice_Date VARCHAR(50),
Customer_id int8,
Country varchar(50),
Quantity int8,
amount int8
)

select * from CRM

COPY CRM FROM 'C:\ARM\customer_relationship.csv' DELIMITER ',' CSV HEADER

select * from CRM

---Q1.What is the total amount of sales for a given date and time range?

select sum(amount) as Total_sales
from CRM
where invoice_date between '12-01-2020 08:26' and '12-01-2020 7:49';

---Q2.What is the total quantity sold for a given date and time range?

select sum(Quantity) as Total_quantity_sales
from CRM
where invoice_date between '12-01-2020 08:26' and '12-01-2020 7:49';

---Q3.Which customer made the most purchases?

select customer_id, count(invoice_id) as num_purchase
from CRM
group by customer_id
order by num_purchase desc
limit 1;

---Q4.What is the average amount per purchase?

select avg(amount) as avg_purchase_amount
from CRM;

---Q5.How many invoices were generated for each customer?

select customer_id, count(invoice_id) as num_invoice 
from CRM
group by customer_id;

---Q6.What is the average quantity per purchase?

select avg(Quantity) as quantity_puchase
from CRM;

---Q7.What is the total revenue generated for each customer?

select customer_id, sum(amount) as Total_revanue
from CRM
group by customer_id;

---Q8.what is the total revanue generated by each customer?

select country, customer_id, sum(amount) as total_amount
from CRM
group by country, customer_id
order by total_amount desc

---Q9. which are the top 5 customer who purchased most?

select customer_id, sum(amount) as total
from CRM
group by customer_id
order by total desc
limit 5

---Q10.Case of Amount category

select invoice_id, customer_id, country, quantity, amount,
case when amount > 10000 then 'High'
	when amount > 5000  then 'Medium'
else 'Low'
End as amount_category
from CRM

